add solution for 03-lection1 01-button
js-tasks-ru/htmlcss-20210916_shkipercore pull request #3
Opened 2021-09-27 21:31 UTC by Shkipercore

2021-09-27 21:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-29 17:29 UTC, GSemikozov requested changes

2021-09-29 17:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    left: 0px;
left + top точно не нужно явно сбрасывать, по умолчанию у нас position: static, а значит никакое позиционирование через top-left невозможно

2021-09-29 17:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
можно сразу на уровне .button задать

2021-09-29 17:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: #FFFFFF;
все цвета забираем из переменных (если нет - нужно создать)

2021-09-29 17:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
можно сразу на уровне .button

2021-09-29 17:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
еще чтобы пользователь не мог взаимодействовать с таким элементом (например чтобы не работал hover или click) задают pointer-events: none

2021-09-30 09:39 UTC, GSemikozov requested changes

2021-09-30 09:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: none;
здесь и ниже - курсор указывать не обязательно, pointer-events: none поставит его в default

2021-09-30 09:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
лучше определить сразу на уровне .button

2021-10-10 03:27 UTC, Shkipercore commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
Исправлено

2021-10-10 03:27 UTC, Shkipercore commented on 03-lection1/01-button/button.css
> +    cursor: none;
Исправлено

2021-10-10 03:27 UTC, Shkipercore commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
Исправлено

2021-10-10 03:27 UTC, Shkipercore commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
Исправлено

2021-10-10 03:27 UTC, Shkipercore commented on 03-lection1/01-button/button.css
> +    color: #FFFFFF;
Исправлено

2021-10-10 03:27 UTC, Shkipercore commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
Исправлено

2021-10-10 03:27 UTC, Shkipercore commented on 03-lection1/01-button/button.css
> +    left: 0px;
Исправлено

2021-10-10 14:50 UTC, GSemikozov approved these changes

2021-10-10 14:50 UTC, merged